config/routes.rb
Rails.application.routes.draw do
  resources :listings

  resources :high_scores

  devise_for :users
  get 'uploads/index'

  get 'uploads/format'

  get 'welcome/features'

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  get 'welcome/pricing'

  resources :invoices

  root to: 'welcome#index'

  get 'uploads/index'
  get 'uploads/format'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  if Rails.env.development?
    has_attached_file :image, 
                    styles: { medium: "200x", thumb: "100x100>" },
                    default_url: "default.jpg"
  else
    has_attached_file :image, 
                    styles: { medium: "200x", thumb: "100x100>" },
                    default_url: "default.jpg",
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :path => ":style/:id_:filename"
  end
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing, html: { multipart: true } do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image ,class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= image_tag listing.image.url %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <%= link_to 'Show', listing, class: "btn btn-link" %>
            <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>
            <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/show.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <div class="col-md-6">
  <div class="thumbnail">
    <%= image_tag @listing.image.url %>
  </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
    <p><%= @listing.description %></p>
  </div>
</div>

<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>