config/routes.rb
Rails.application.routes.draw do
  resources :listings

  resources :high_scores

  devise_for :users
  get 'uploads/index'

  get 'uploads/format'

  get 'welcome/features'

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get 'welcome/faq'

  get 'welcome/pricing'

  resources :invoices

  root to: 'welcome#index'

  get 'uploads/index'
  get 'uploads/format'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
          <li><%= link_to "About us", welcome_about_path %></li>
          <li><%= link_to "Contact", welcome_contact_path %></li>
          <li><%= link_to "Features", welcome_features_path %></li>
          <li><%= link_to "FAQ", welcome_faq_path %></li>
          <li><%= link_to "Pricing", welcome_pricing_path %></li>
          <li><%= link_to "Invoices", invoices_path %></li>
          <li><%= link_to "Listings", listings_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login", root_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnterpriseApe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <!-- <p class="notice"><%= notice %></p> -->
  <!-- <p class="alert"><%= alert %></p> -->
  
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>